// // user Auth
export const USER_SIGNIN = 'USER_SIGNIN'
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS'
export const USER_SIGNIN_FAILURE = 'USER_SIGNIN_FAILURE'

export const USER_AUTH_STATUS="USER_AUTH_STATUS";
export const USER_AUTH_STATUS_SUCCESS="USER_AUTH_STATUS_SUCCESS";
export const USER_AUTH_STATUS_FAILURE="USER_AUTH_STATUS_FAILURE";

export const USER_SIGNOUT = 'USER_SIGNOUT'
export const USER_SIGNOUT_SUCCESS = 'USER_SIGNOUT_SUCCESS'
export const USER_SIGNOUT_FAILURE = 'USER_SIGNOUT_FAILURE'

export const USER_SIGNUP = "USER_SIGNUP"
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS"
export const USER_SIGNUP_FAILURE = "USER_SIGNUP_FAILURE"

export const USER_FORGOT_PAASWORD = 'USER_FORGOT_PAASWORD';
export const USER_FORGOT_PAASWORD_SUCCESS = 'USER_FORGOT_PAASWORD_SUCCESS';
export const USER_FORGOT_PAASWORD_FAILURE = 'USER_FORGOT_PAASWORD_FAILURE';

export const USER_CHANGE_PASSWORD = 'USER_CHANGE_PASSWORD';
export const USER_CHANGE_PASSWORD_SUCCESS = 'USER_CHANGE_PASSWORD_SUCCESS';
export const USER_CHANGE_PASSWORD_FAILURE = 'USER_CHANGE_PASSWORD_FAILURE';

export const USER_INFO = 'USER_INFO';
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const USER_INFO_FAILURE = 'USER_INFO_FAILURE';

export const USER_INFO_UPDATE = 'USER_INFO_UPDATE';
export const USER_INFO_UPDATE_SUCCESS = 'USER_INFO_UPDATE_SUCCESS';
export const USER_INFO_UPDATE_FAILURE = 'USER_INFO_UPDATE_FAILURE';


// task
export const CREATE_TASK = "CREATE_TASK"
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS"
export const CREATE_TASK_FAILURE = "CREATE_TASK_FAILURE"

export const RETRIEVE_TASK = "RETRIEVE_TASK"
export const RETRIEVE_TASK_SUCCESS = "RETRIEVE_TASK_SUCCESS"
export const RETRIEVE_TASK_FAILURE = "RETRIEVE_TASK_FAILURE"

export const UPDATE_TASK = "UPDATE_TASK"
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS"
export const UPDATE_TASK_FAILURE = "UPDATE_TASK_FAILURE"

export const DELETE_TASK = "DELETE_TASK"
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS"
export const DELETE_TASK_FAILURE = "DELETE_TASK_FAILURE"


// ngrok url
export const UPDATE_NGROKURL = "UPDATE_NGROKURL"
export const UPDATE_NGROKURL_SUCCESS = "UPDATE_NGROKURL_SUCCESS"
export const UPDATE_NGROKURL_FAILURE = "UPDATE_NGROKURL_FAILURE"
